export enum IconNamesEnum{
  AGREGAR_ICON="agregar-icon",
  PORTAPAPELES_ICON="portapapeles-icon",
  ESCUDO_ICON="escudo-icon",
  EDITAR_ICON="editar-icon",
  ELIMINAR_ICON="eliminar-icon",
  APROBACION_ICON="aprobacion-icon",
  REPORTES_ICON="reportes-icon",
  IDENTITY_ICON="identity-icon",
  KEY_ICON="key-icon",
  MENU_ICON="menu-icon",
  CLOSE_ICON="close-icon",
  DEFAULT_ICON="default-icon",
  MOVISTAR_ICON="movistar-icon",
  ALERT = "Alerta_1Light",
  ADD_LIGTH = "Añadir_1Light",
  PADLOCK = "Candado abierto_2Regular",
  SHUT_ICON = "Cerrar_1Light",
  PUZZLE2_ICON = "Puzzle _2Regular",
  IDENTITY_USER = "Usuario_Micuenta_persona_2Regular",
}
